CREATE TABLE IF NOT EXISTS "FlashSale" (
  "id" TEXT NOT NULL,
  "productId" TEXT NOT NULL,
  "discount" DOUBLE PRECISION NOT NULL,
  "startAt" TIMESTAMP(3) NOT NULL,
  "endAt" TIMESTAMP(3) NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "FlashSale_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "FlashSale_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
